### ISSUE TITLE
与FPGA的关联性

### ISSUE THREAD

**Issue by jimmy-adams** [xddcore/OpenNNA2.0#2]
你好，
看到你的工作，感觉很酷炫！然后想问一下，Readme中提到的与FPGA资源的联系，我的理解是用linux的驱动或者更用户定义化为算子，通过FPGA资源进行运算的加速。不知道理解的是否正确？
其中与FPGA的兼容，是用什么样的方法去设计的呢？

谢谢

**Comment by xddcore** [comment]
理解正确。卷积神经网络算子使用c++编写，并通过vivado HLS综合为硬件电路。
